# Generated by Django 5.2.4 on 2025-08-02 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_remove_carletonemail_id_alter_carletonemail_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membership',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='MembershipUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.membership')),
            ],
        ),
    ]
