# Generated by Django 5.2.4 on 2025-08-02 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_membership_name_membershipupdatehistory_change_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='engineer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membership',
            name='program',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipupdatehistory',
            name='new_engineer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipupdatehistory',
            name='new_paid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipupdatehistory',
            name='new_program',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipupdatehistory',
            name='new_revoked',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
