# Generated by Django 5.2.4 on 2025-08-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_membership_engineer_membership_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='signup_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='membershipupdatehistory',
            name='change_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
